### ISSUE TITLE
Can userAgentRegExps is added by Meteor.settings?

### ISSUE THREAD

**Issue by fangjj** [artlimes/meteor-chrome-headless-spiderable#2]
I'm in china, so want to add some other different UserAgentRegExps, so can be added by Meteor.settings. that is nice.

**Comment by prosf** [comment]
@fangjj  You can override them by importing the Spiderable plugin in Server-side code:
`import { Spiderable } from "meteor/artlimes:meteor-chrome-headless-spiderable";`


and then define your preferred Spiders list:

`
Spiderable.userAgentRegExps = [
  /360spider/i,
  /adsbot-google/i,
..etc
]
`

**Comment by fangjj** [comment]
that's fine.
