### ISSUE TITLE
how to improve the speed of visiting the page at first time. 

### ISSUE THREAD

**Issue by fangjj** [artlimes/meteor-chrome-headless-spiderable#3]
I test curl The first visting the page takes 20s. how to improved it?

**Comment by prosf** [comment]
@fangjj 
Use checkAfterSeconds setting:

`Meteor.settings.checkAfterSeconds = 0;`

or any value below 10 that seems to work best for you.

**Comment by fangjj** [comment]
yeah, that is fine.
